### ISSUE TITLE
Hangs with `div` in indices?

### ISSUE THREAD

**Issue by mcabbott** [JuliaSIMD/LoopVectorization.jl#250]
Here's a stranger bug, this seems to run forever?
```julia
function act!(R, A, B, ax_i=1:4, ax_j=Base.OneTo(4))
    for j in ax_j
        for i in ax_i
            R[i, j] = A[2i + (j - 1) ÷ 2] + 0 * B[j]
        end
    end
    R
end
function act_avx!(R, A, B, ax_i=1:4, ax_j=Base.OneTo(4))
    @avx for j in ax_j
        for i in ax_i
            R[i, j] = A[2i + (j - 1) ÷ 2] + 0 * B[j]
        end
    end
    R
end

A, B = rand(10), rand(4)
act!(zeros(4,4), A, B)
act_avx!(zeros(4,4), A, B)  # needs ^C to exit?
```
Also found by CI in https://github.com/mcabbott/Tullio.jl/pull/79, no urgent need... possibly I will remove the handling of `÷` in indices entirely. (This has bugs, e.g. https://github.com/mcabbott/Tullio.jl/issues/76)

But I presume `@avx` should either reject this at once, or work.

**Comment by chriselrod** [comment]
Just fixed it on master.

**Comment by chriselrod** [comment]
Arbitrary functions that return integers should work; the `clamp` fix in the commit addressed that.
But I also realized `div` was missing from the cost table, so I added it.

**Comment by chriselrod** [comment]
Fixed and releasing shortly.
