### ISSUE TITLE
Bug in scalar reduction?

### ISSUE THREAD

**Issue by mcabbott** [JuliaSIMD/LoopVectorization.jl#251]
One more! Again from CI, not sure why this case should be problematic:
```julia
function fwd(r22::AbstractArray{T}, x, r312, ax_b=axes(x,2), ax_β=axes(r312,2), ax_a=axes(r312,2), ax_c=axes(r312,1)) where T
        acc = zero(T)
        # for c in ax_c  # works fine without @avx
        @avx for c in ax_c
            for a in ax_a
                for β in ax_β
                    for b in ax_b
                        acc = acc + r22[b, β] * x[a, b, c] * r312[c, a, β]
                    end
                end
            end
        end
        acc
end
r22, x, r312 = rand(2,2), rand(1,2,3), rand(3,1,2)
fwd(r22, x, r312) # UndefVarError: ####op#568_0 not defined

fwd(rand(3,3), rand(3,3,3), rand(3,3,3)) # similar, so not about size=1 dimensions
```

**Comment by chriselrod** [comment]
There's the joke about cache invalidation and naming things being the two hardest things in programming.
I can't speak about the former, but LoopVectorizaiton.jl certainly thinks it is the latter...

The rewrite will handle that totally differently.

**Comment by mcabbott** [comment]
Proof that `gensym()` doesn't solve all naming difficulties! 

But sure, no rush, this one's skipped in testing & didn't bite anyone in real life.

**Comment by chriselrod** [comment]
Fixed on master, releasing soon.
With AVX512, it is also much faster now than it was when/if it worked earlier, due to adding a workaround for a bug in LLVM where it starts spilling registers to an absurd degree (when it shouldn't be spilling at all) when there are too many phi nodes, or something of that sort.
