### ISSUE TITLE
Precompilation fails on 32bit systems

### ISSUE THREAD

**Issue by devmotion** [JuliaSIMD/LoopVectorization.jl#258]
The latest release of LoopVectorization (0.12.13) fails to precompile on 32bit systems: https://github.com/TuringLang/Turing.jl/pull/1599/checks?check_run_id=2483639317#step:6:257 It seems this is caused by changes to src/precompile.jl in https://github.com/JuliaSIMD/LoopVectorization.jl/pull/254, more precisely by some hardcoded Int64. Maybe one should just generally replace all Int64 with Int?

**Comment by chriselrod** [comment]
Yeah, I'll try that. It's easy to install 32 bit Julia on 64 bit systems (i.e., just download it from the downloads page like normal), so I'll try that. Some functions may specifically want `Int64`, so it's worth double checking.

**Comment by chriselrod** [comment]
I happened to have an old copy (1.6-rc1) of 32 bit Julia laying around:
```julia
julia> using LoopVectorization

julia> versioninfo()
Julia Version 1.6.0-rc1
Commit a58bdd9010 (2021-02-06 15:49 UTC)
Platform Info:
  OS: Linux (i686-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz
  WORD_SIZE: 32
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake-avx512)
Environment:
  JULIA_NUM_THREADS = auto

(@v1.6) pkg> st LoopVectorization
      Status `~/.julia/environments/v1.6/Project.toml`
  [bdcacae8] LoopVectorization v0.12.14 `~/.julia/dev/LoopVectorization`
```
Simply replacing all `Int64 -> Int` did the trick.
