### ISSUE TITLE
Wrong result with mix of multiplication and addition within avx accumulation

### ISSUE THREAD

**Issue by oschulz** [JuliaSIMD/LoopVectorization.jl#259]
I seem to be hitting some bug in LoopVectorization when mixing multiplication and addition within an `@avx` accumulation:

```julia
using LoopVectorization

let A = rand(3,3), B = rand(3)
    C1 = zero(A)
    C2 = zero(A)

    @avx for j in axes(A,1), k in axes(A,2)
        C1[j] += A[j,k] * B[k]
        C2[j] += A[j,k] * B[k] - 0 * B[j]
    end
    sum(C1), sum(C2)
end
```

`C1` and `C2` differ (but shouldn't, obviously).

The above is an MWE, obviously, but this came from a real-life use case.

**Comment by chriselrod** [comment]
I fixed it and added it to the tests. This falls under the "LoopVectorization sucks at naming things" class of bugs, which is probably the source of half the issues and will be done completely differently/in an actually robust fashion in the rewrite.
Basically, what went wrong:
```julia
for j in axes(A,1)
    x1 = -0*B[j]
    for k in axes(A,2)
        x2 = A[j,k] * B[k] + x1
    end
end
```
The temp fix was to just call all of them "x2", but that's not actually confirming that some of its other name mangling is done the same way (e.g, it could be "x2_2_0" and "x2__0" at different places), but hopefully this covers your case.
If it doesn't, you can file another issue. If it does, the sooner that whole system is replaced, the better.

**Comment by oschulz** [comment]
Thanks for much for the super-fast fix!
