### ISSUE TITLE
Error when loading LoopVectorization after ForwardDiff with --compiled-modules=no

### ISSUE THREAD

**Issue by mfsch** [JuliaSIMD/LoopVectorization.jl#268]
I ran into this error when using OrdinaryDiffEq.jl with `julia --compiled-modules=no`:

```
┌ Warning: Error requiring `ForwardDiff` from `LoopVectorization`
│   exception =
│    LoadError: UndefVarError: Dual not defined
│    in expression starting at ~/.julia/packages/LoopVectorization/09Hhf/src/simdfunctionals/vmap_grad.jl:6
└ @ Requires ~/.julia/packages/Requires/7Ncym/src/require.jl:49
```

The most minimal case I managed to narrow it down to is having a new project with only `ForwardDiff` and `LoopVectorization` as dependencies, then starting Julia with `--compiled-modules=no` and first importing `LoopVectorization`, then `ForwardDiff`. When compiled modules are activated or when `ForwardDiff` is imported first, the error does not appear.

**Comment by chriselrod** [comment]
Is this a Requires bug?

**Comment by mfsch** [comment]
I’ve reported it as https://github.com/JuliaPackaging/Requires.jl/issues/105 – let’s see if the Requires people know why this is happening.

My use case for `--compiled-modules=no` is that the Julia precompilation mechanism doesn’t interact well with MPI, so if you’re running an MPI program you can get errors if multiple instances of Julia are trying to precompile a package simultaneously. Running without compiled modules avoids this issue and is [recommended in the MPI.jl documentation](https://juliaparallel.github.io/MPI.jl/stable/knownissues/).

**Comment by chriselrod** [comment]
On master:
```julia
# julia -q --startup=no --compiled-modules=no
julia> using LoopVectorization

julia> using ForwardDiff

julia>
```
Still a Requires bug, but we can work around it here, so it works on master.
