### ISSUE TITLE
Allow custom setindex! methods

### ISSUE THREAD

**Issue by Octogonapus** [JuliaSIMD/LoopVectorization.jl#276]
I would like to get LoopVectorization to "understand", for lack of a better word, a simple function I have in a vectorized loop. I get this error `Function increment_subweight! not recognized.` from `@ LoopVectorization ~/.julia/packages/LoopVectorization/NmwAk/src/modeling/graphs.jl:1112`. That line is part of a conditional that checks `if finex === :setindex!` or throws that error.

My function is essentially `setindex!`, but I haven't added a method to it because I effectively have two set index methods:
```julia
@propagate_inbounds increment_weight!(h::FixedWidthHistogram, is...) = h.weights[is...] += 1
@propagate_inbounds increment_subweight!(h::FixedWidthHistogram, is...) = h.subweights[is...] += 1
```

My loop looks like this:
```julia
@turbo for i = 0:3
    @inbounds tx = img1[r+i, c]
    @inbounds ty = img2[r+i, c]
    ix = bin_search(h, tx)
    iy = bin_search(h, ty)
    @inbounds increment_subweight!(h, ix, iy, i + 1)
end
```

I think it would be great if there was a way for LoopVectorization to understand that `increment_subweight!` is essentially just `setindex!`. I don't simply use `setindex!` directly because this is meant to be generic code that doesn't need to understand the internal structure of `h`, and assuming there is a member `subweights` of `h` seems less Julian to me. Of course, as a workaround, I can add that to the API contract.

I am using LoopVectorization v0.12.25 and Julia v1.6.1.

**Comment by chriselrod** [comment]
Until LoopVectorization gets a new front end that's better integrated with the compiler, it won't be able to peer through the abstractions like `increment_subweight!` and understand what your code is doing well enough to optimize it.

you could try something like
```julia
getweights(h::FixedWidthHistogram) = h.weights
w = getweights(h)
@turbo for i = 0:3
    # do stuff
    w[ix, iy, i+1] += 1
end
```

**Comment by Octogonapus** [comment]
Yeah, a workaround like that is fine. I will close this unless you want to use it to track a new feature in the front end.
