### ISSUE TITLE
removing `maybestaticsize` broke StrideArrays

### ISSUE THREAD

**Issue by ranocha** [JuliaSIMD/LoopVectorization.jl#285]
3738a05a0f69d1b680fbd13fb9e98b0a1c4cd796 removed `maybestaticsize` from LoopVectorization.jl, which is imported in https://github.com/chriselrod/StrideArrays.jl/blob/68897df5ee8eb4d3a2b453888dcabf43b9095bd5/src/StrideArrays.jl#L14 
This broke some of our tests.

**Comment by ranocha** [comment]
Related to https://github.com/JuliaLinearAlgebra/Octavian.jl/issues/100

**Comment by chriselrod** [comment]
Thanks for reporting this.
As soon as this is merged, I'll make a release: https://github.com/JuliaLinearAlgebra/Octavian.jl/pull/101
Once that's released, I'll push an update to `StrideArrays` dropping it.
