### ISSUE TITLE
StackOverflow with SpecialFunction

### ISSUE THREAD

**Issue by lstagner** [JuliaSIMD/LoopVectorization.jl#293]
I'm running into a StackOverflow error when calculating an elliptic integral from SpecialFunctions.jl

```julia
using LoopVectorization, SpecialFunctions
function ellipk_test(N)
    g = zeros(N)
    m = fill(0.5,N)
    @avx for i=1:N
        g[i] = ellipk(m[i])
    end
end
ellipk_test(100)

StackOverflowError:
Stacktrace:
 [1] ellipk(x::VectorizationBase.Vec{4, Float64}) (repeats 79984 times)
   @ SpecialFunctions ~/.julia/packages/SpecialFunctions/Bm58S/src/ellip.jl:353
```

Funnily if I remove the array argument then it runs fine
```julia
function ellipk_test2(N)
    g = zeros(N)
    @avx for i=1:N
        g[i] = ellipk(0.5)
    end
end
ellipk_test2(100) #<--- no error
```

**Comment by chriselrod** [comment]
> Funnily if I remove the array argument then it runs fine

With the array argument, LoopVectorization will try to SIMD the expression, requiring SIMD support for the called function.
That is tracked here: https://github.com/JuliaSIMD/LoopVectorization.jl/issues/233

Without the array argument, there's no need for SIMD evaluation, so it gets called just once with `0.5`, and then fills `g` with that value.

I'll close this issue in favor of #233, as that tracks `ellipk` and other special functions.

**Comment by chriselrod** [comment]
PRs to VectorizationBase.jl (or in the future, LLVMCalls.jl) or SLEEFPirates.jl adding a SIMD version of any of these functions, including ellipk, would be much appreciated.

However, implementing them is not trivial.
A difficulty compared to scalar implementations (e.g. [here](https://github.com/JuliaMath/SpecialFunctions.jl/blob/5f0a078c21b604ed645be7088d2cc3ba12c4b7e4/src/ellip.jl#L42)) is that you can't efficiently branch on values.
