### ISSUE TITLE
Return Warning when LoopVectorization Fails

### ISSUE THREAD

**Issue by ParadaCarleton** [JuliaSIMD/LoopVectorization.jl#296]
It would be nice to have a warning telling me when LoopVectorization fails. Concerns were raised about performance/repetitive warnings, so I'd suggest a keyword argument, `testing`, which is `false` by default but can be set to `true`, in which case a failing LoopVectorization will throw an error.

**Comment by chriselrod** [comment]
I added `warn_check_args=true` as an optional keyword argument.
With that argument, it'll emit a warning on the first evaluation if the fallback loop is executed.
You can see an example in [test/fallback.jl](https://github.com/JuliaSIMD/LoopVectorization.jl/blob/9aa0211e9547eec970a02fc3e052f94baaabb137/test/fallback.jl#L36-L37).
