### ISSUE TITLE
Incorrect results. Nested indexing?

### ISSUE THREAD

**Issue by deklanw** [JuliaSIMD/LoopVectorization.jl#325]
Getting no error but adding `@turbo` to a loop seems to be giving different results than without. Toy reproduction extracted from my code here

```julia
using Random
using LoopVectorization
using StatsBase

# graph of 2000 nodes, split into 100 blocks
N = 2000
B = 100

# randomly assign nodes to blocks
block_membership = Random.rand!(zeros(Int64, N), 1:B)

# let's pretend a given node has 300 neighbors
row = sample(1:N, 300, replace=false)

# now let's count the block membership of its neighbors

# first with turbo
neighbor_block_sums = zeros(Int64, B)
@turbo for j in 1:length(row)
    n = row[j]
    neighbor_block_sums[block_membership[n]] += 1
end

# then without
neighbor_block_sums2 = zeros(Int64, B)
for j in 1:length(row)
    n = row[j]
    neighbor_block_sums2[block_membership[n]] += 1
end

@assert neighbor_block_sums == neighbor_block_sums2
```

**Comment by chriselrod** [comment]
This is because it's reading/writing in parallel (using SIMD instructions).
To be simple, let's say your SIMD vector width is 2.
If `block_membership = [1,1]`, then it will read from `neighbor_block_sums[1]` twice, add 1 to both, and then store both answers to the sample place.

**Comment by deklanw** [comment]
@chriselrod I see. I thought about that being a possibility, but what's the difference between that and this case

```julia
sum1 = 0
@turbo for i in 1:1000
    sum1 += 1
end

sum2 = 0
for i in 1:1000
    sum2 += 1
end

@assert sum1 == sum2
```

Do we not also "read" sum1 to add 1 to it? Does it have to do with stack vs heap?

**Comment by chriselrod** [comment]
LoopVectorization recognizes reductions like that, and creates parallel accumulators.
In principle, the same thing thing would be possible for binned accumulation.

However, on current CPUs, SIMD doesn't normally speed up gathers/scatters (loading/storing non-contiguous memory with SIMD isntructions) vs multiple equivalent scalar operations, so I think it's also unlikely to help performance here.
It might on some AVX512 CPUs, and perhaps with SVE (particularly the A64FX, where these operations are faster than scalar equivalents when data comes from the same cacheline [its cache-lines are also very large at 256 bytes, vs the 64 bytes typical of x86 CPUs].

**Comment by deklanw** [comment]
You lost me a bit there. Will have to do some reading. Fwiw, the `@turbo` version, incorrect as it is, is about 16x faster.

Related?
https://stackoverflow.com/questions/12985949/methods-to-vectorise-histogram-in-simd

**Comment by deklanw** [comment]
Conveniently, there is already a Julia library which tackles this. Hurray Julia ecosystem!

https://octogonapus.github.io/FastHistograms.jl

Closing, since this is resolved.
