### ISSUE TITLE
the PNGs in docs are killing pkg server bandwidth

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaSIMD/LoopVectorization.jl#349]
LoopVectorization is, quite rightly, very popular. And very well documented (kudos!). However, the fact that there are a bunch of semi-large PNG files in the `docs` directory is causing the package to be quite large for a Julia package—14 MB. The combination of these things is taking a bit of a toll on our package server bandwidth. There's a number of possible systematic fixes that @staticfloat and I are discussing, but the simplest fix would be to replace the beefy, uncompressed PNGs with a lighter, more compression-friendly format.

**Comment by chriselrod** [comment]
> An alternative. You can save the reference images to another branch(say, docs-assets) and then linked back. PkgServer only packs the release branch instead of the entire repository.
> 
> CRef [JuliaImages/DitherPunk.jl#33 (comment)](https://github.com/JuliaImages/DitherPunk.jl/issues/33#issuecomment-896505737)

Thanks for the suggestion -- seemed simple enough, so that's what I've done.
The plots are now in the [docsassets](https://github.com/JuliaSIMD/LoopVectorization.jl/tree/docsassets/docs/src/assets) branch.

**Comment by StefanKarpinski** [comment]
Thanks, @chriselrod!
