### ISSUE TITLE
`mod` not supported in LoopVectorization

### ISSUE THREAD

**Issue by Chiil** [JuliaSIMD/LoopVectorization.jl#361]
I use a `mod` in my loop and LoopVectorization gives: `ERROR: LoadError: mod not defined for VectorizationBase.Vec{8, Float64}
` in statement `fi = mod(i_pos, 1)`

Would it be possible to support `mod`?

**Comment by chriselrod** [comment]
We could add a `Vec{8,Float64}` definition to VectorizationBase.

**Comment by chriselrod** [comment]
Should be fixed by https://github.com/JuliaSIMD/VectorizationBase.jl/commit/1b6cdc4d721bce66f724ef08d831994720ab420b
