### ISSUE TITLE
Roadway to optimize arrays containing non-primitive types

### ISSUE THREAD

**Issue by islent** [JuliaSIMD/LoopVectorization.jl#363]
Hello! I have the urgent need to handle arrays containing non-primitive types https://github.com/JuliaSIMD/LoopVectorization.jl/discussions/242. StructArrays (already using it, however I might need something like StructArray of StructArrays) and [reinterpret](https://juliasimd.github.io/LoopVectorization.jl/latest/examples/datetime_arrays/) may complicate my own code project. I noticed [future plans](https://juliasimd.github.io/LoopVectorization.jl/latest/future_work/) and wondering when this would be implemented.

To see whether I can do it myself, I tried on reading (part of) the source code and [Developer Documentation](https://juliasimd.github.io/LoopVectorization.jl/latest/devdocs/overview/). However, I have no idea where to start. Is there any plans, or instructions?

**Comment by chriselrod** [comment]
I am working on this, at a rate of at least a couple hours per week.
At that rate, it's hard to predict how long it'll take. My guess at the moment is 6 months if I'm able to pick up the pace.
I'd probably have to take several weeks off of work toward the end to finish up once I get close, which I am not yet.

The roadmap is basically to write a new library that we can plugin as an LLVM pass.
The goal there is to solve a large number of issues that are fundamental to the current approach, with support for non-primitive types being one of them.

**Comment by islent** [comment]
Many thanks, and good luck! Comment here if you need any help
