### ISSUE TITLE
Remove Requires.jl usage

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaSIMD/LoopVectorization.jl#372]
https://github.com/JuliaSIMD/LoopVectorization.jl/blob/v0.12.99/src/LoopVectorization.jl#L123-L129

Those are some of the most used packages in the Julia ecosystem. I would assume that like 99% of users have those packages, yet they all get a startup time from it. Separate module? I don't know, but having that be Requires.jl usage is a bit suspect given the prevalence of those packages.

**Comment by chriselrod** [comment]
This is a breaking change, so would require a bump to 0.13. Too bad, I was hoping to hit 0.12.100.

**Comment by chriselrod** [comment]
Feel free to make a PR that strips it out.
