### ISSUE TITLE
`@avx` for loop whose body is not a `block` causes  `StackOverflowError`

### ISSUE THREAD

**Issue by wangl-cc** [JuliaSIMD/LoopVectorization.jl#395]
I'm trying to generate loops with macro and use `@avx` to accelerate it. For examples,
```julia
macro gen_loop_avx_1(ex)
    sym, ind = ex.args
    loop_body = :(ret[$ind] = $sym[$ind])
    loop = Expr(:for, :($ind = axes($sym, 1)), loop_body)
    return esc(:(@avx $loop))
end
```
this macro will generate a loop like this with `@macroexpand1 @gen_loop_avx_1 V[i]`
```julia
@avx for i = axes(V, 1)
    ret[i] = V[i]
end
```
However, when expand macros with `@macroexpand`, I receives a `StackOverflowError`.

A solution is make `loop_body` becomes a `block`:
```Julia
macro gen_loop_avx_2(ex)
    sym, ind = ex.args
    loop_body = Expr(:block, :(ret[$ind] = $sym[$ind]))
    loop = Expr(:for, :($ind = axes($sym, 1)), loop_body)
    return esc(:(@avx $loop))
end
```
this macro will generate the similar loop but its body is a block and works well with `@avx`.

Then, when I check my original code, the loop body is defined as a `block` until
`MacroTools.flatten` remove it, like this:
```Julia
macro gen_loop_avx_3(ex)
    sym, ind = ex.args
    loop_body = Expr(:block, :(ret[$ind] = $sym[$ind]))
    loop = Expr(:for, :($ind = axes($sym, 1)), loop_body)
    return esc(:(@avx $(MacroTools.flatten(loop))))
end
```
which will cause `StackOverflowError` again.

In my opinion, the `@avx` checking the loop body if it is a block may be helpful.

**Comment by chriselrod** [comment]
The simplest fix may be to check if it is a block, and if not wrap it with one:
https://github.com/JuliaSIMD/LoopVectorization.jl/blob/77d0efb00184305fd8c4b9cfe1b5c5d28d9c108f/src/constructors.jl#L161-L162
Feel free to make a PR.

**Comment by wangl-cc** [comment]
@chriselrod Hi, I'm working on it, where should tests about this issue be put?

**Comment by chriselrod** [comment]
Feel free to create a new file called "parsing_inputs.jl" or something.
For where to put the `include`, put it in whichever group is fastest:
https://github.com/JuliaSIMD/LoopVectorization.jl/blob/77d0efb00184305fd8c4b9cfe1b5c5d28d9c108f/test/grouptests.jl#L9
Looking at a recent test run, it looks like that might be the first group:
https://github.com/JuliaSIMD/LoopVectorization.jl/actions/runs/2139986660

**Comment by wangl-cc** [comment]
@chriselrod Thanks for your patience.
