### ISSUE TITLE
Regression in version 0.12.130

### ISSUE THREAD

**Issue by karajan9** [JuliaSIMD/LoopVectorization.jl#436]
Some of my code isn't able to be `@turbo`ed anymore since version 0.12.130. Specifically, I'm getting a
```
┌ Warning: #= ... =#:
│ `LoopVectorization.check_args` on your inputs failed; running fallback `@inbounds @fastmath` loop instead.
```
and ~3x slowdown on code that worked fine on version 0.12.129.

I'm not sure if I'll be allowed to share the code. Is there any information I could help with while I try to figure this out?

**Comment by karajan9** [comment]
After looking through the changes I think it was making `safe=true` the default.
Since replacing every instance of `a^2` by `a*a` and `ifelse` by `my_ifelse(decider, a, b) = decider * a + (1 - decider) * b` I have achieved the old performance again.
I'm not sure if that was the intention behind the change but if so I can certainly live with the changes I made.

**Comment by chriselrod** [comment]
Hi, regressions where `@turbo` worked before were not the intention.
`can_turbo` should return `true` for `ifelse` and `^`.
I'll have changes shortly that make this so.

Please feel free to file issues or create PRs for any more such problems.

**Comment by chriselrod** [comment]
Please let me know if your original versions encounter any problems. They should work now.

**Comment by karajan9** [comment]
I can confirm that the original code now again runs with original speed (and no warning).
Thanks for looking into this and all the work you have been doing on this project! Truly a gamechanger.
