### ISSUE TITLE
A possible typo in `cdot_swizzle`

### ISSUE THREAD

**Issue by cuihantao** [JuliaSIMD/LoopVectorization.jl#443]
There might be a typo here: https://github.com/JuliaSIMD/LoopVectorization.jl/blob/be2af94ddacbb958d8995c58b4da4603def6fffc/test/shuffleloadstores.jl#L26

`Vec` is not defined. What should it be? Neither `Vector` or `vec` takes two zeros.

**Comment by chriselrod** [comment]
It should be `VectorizationBase.Vec`.

**Comment by cuihantao** [comment]
Thanks!
