### ISSUE TITLE
Error with large number of array references 

### ISSUE THREAD

**Issue by johnbcoughlin** [JuliaSIMD/LoopVectorization.jl#450]
I am trying to use `LoopVectorization` to speed up a generated function with a very large loop body. I get the following error:
```
BoundsError: attempt to access 328-element Vector{LoopVectorization.ArrayReferenceMeta} at index [0]
 Stacktrace:
    [1] getindex
      @ ./array.jl:924 [inlined]
    [2] getindex
      @ ./abstractarray.jl:1244 [inlined]
    [3] mref_elbytes
      @ ~/.julia/packages/LoopVectorization/FMfT8/src/reconstruct_loopset.jl:607 [inlined]
    [4] add_op!(ls::LoopVectorization.LoopSet, instr::LoopVe ... es::Vector{Int64})
      @ LoopVectorization ~/.julia/packages/LoopVectorization/FMfT8/src/reconstruct_loopset.jl:624
    [5] add_ops!(ls::LoopVectorization.LoopSet, instr::Vecto ... edv::Vector{Bool})
      @ LoopVectorization ~/.julia/packages/LoopVectorization/FMfT8/src/reconstruct_loopset.jl:738
    [6] avx_loopset!(ls::LoopVectorization.LoopSet, instr::V ... Core.SimpleVector)
      @ LoopVectorization ~/.julia/packages/LoopVectorization/FMfT8/src/reconstruct_loopset.jl:868
    [7] _turbo_loopset(OPSsv::Any, ARFsv::Any, AMsv::Any, LP ... t64, Int64, Bool})
      @ LoopVectorization ~/.julia/packages/LoopVectorization/FMfT8/src/reconstruct_loopset.jl:933
....
```
Still working on a minimal reproduction. It seems to me this is related to the casting of indices to a `UInt8`. I'm happy to try and tackle this if you can give some guidance.

**Comment by chriselrod** [comment]
> It seems to me this is related to the casting of indices to a UInt8. I'm happy to try and tackle this if you can give some guidance.

There are places where we do have a reason to do that, e.g. when using a single `UInt128` to represent a bunch of values.

That superficially does not seem to be the case here:
https://github.com/JuliaSIMD/LoopVectorization.jl/blob/c74cd3362866d2b8527b0432d371fde3a8871b91/src/condense_loopset.jl#L150-L161
I'd have to look more to see if there's another place storing these as bits within a larger `UInt` or `UInt128`. If not great. If the former, we could bump it up to a `UInt128` and double the number of bits. If the latter, more changes would be needed.

The purpose of these is to transfer a description of the loops into an `@generated` function.

Why do you have 328 unique arrays you're using in the same loop?
That is a lot of arrays.

**Comment by johnbcoughlin** [comment]
Hmmm, I definitely don't have 328 distinct arrays. I believe I know how to get to that number though. I have 81 pairs of statements like this:
```
                #= /Users/jack/projects/VlasovMDG/src/fulltensor/2d2v/free_transport.jl:193 =#
df_M[9, 9, λx, λy, λvx, λvy] -= a_y * a_vx * a_vy * ((((((0 + (a_vx * 0.10666666666666669) * ifelse(b_vx_gt_0, f[7, 8, λx, λy, λvx, λvy] * 0.4, f[7, 8, λx + 1, λy, λvx, λvy] * 0.4)) + (b_vx * 0.16000000000000003) * ifelse(b_vx_gt_0, f[7, 9, λx, λy, λvx, λvy] * 0.4, f[7, 9, λx + 1, λy, λvx, λvy] * 0.4)) + (a_vx * 0.10666666666666669) * ifelse(b_vx_gt_0, f[8, 8, λx, λy, λvx, λvy] * 0.4, f[8, 8, λx + 1, λy, λvx, λvy] * -0.4)) + (b_vx * 0.16000000000000003) * ifelse(b_vx_gt_0, f[8, 9, λx, λy, λvx, λvy] * 0.4, f[8, 9, λx + 1, λy, λvx, λvy] * -0.4)) + (a_vx * 0.10666666666666669) * ifelse(b_vx_gt_0, f[9, 8, λx, λy, λvx, λvy] * 0.4, f[9, 8, λx + 1, λy, λvx, λvy] * 0.4)) + (b_vx * 0.16000000000000003) * ifelse(b_vx_gt_0, f[9, 9, λx, λy, λvx, λvy] * 0.4, f[9, 9, λx + 1, λy, λvx, λvy] * 0.4))
                #= /Users/jack/projects/VlasovMDG/src/fulltensor/2d2v/free_transport.jl:194 =#
                df_M[9, 9, λx + 1, λy, λvx, λvy] += a_y * a_vx * a_vy * ((((((0 + (a_vx * 0.10666666666666669) * ifelse(b_vx_gt_0, f[7, 8, λx, λy, λvx, λvy] * 0.4, f[7, 8, λx + 1, λy, λvx, λvy] * 0.4)) + (b_vx * 0.16000000000000003) * ifelse(b_vx_gt_0, f[7, 9, λx, λy, λvx, λvy] * 0.4, f[7, 9, λx + 1, λy, λvx, λvy] * 0.4)) + (a_vx * 0.10666666666666669) * ifelse(b_vx_gt_0, f[8, 8, λx, λy, λvx, λvy] * 0.4, f[8, 8, λx + 1, λy, λvx, λvy] * -0.4)) + (b_vx * 0.16000000000000003) * ifelse(b_vx_gt_0, f[8, 9, λx, λy, λvx, λvy] * 0.4, f[8, 9, λx + 1, λy, λvx, λvy] * -0.4)) + (a_vx * 0.10666666666666669) * ifelse(b_vx_gt_0, f[9, 8, λx, λy, λvx, λvy] * 0.4, f[9, 8, λx + 1, λy, λvx, λvy] * 0.4)) + (b_vx * 0.16000000000000003) * ifelse(b_vx_gt_0, f[9, 9, λx, λy, λvx, λvy] * 0.4, f[9, 9, λx + 1, λy, λvx, λvy] * 0.4))
```
So if it's counting a separate `ArrayReferenceMeta` for each of `df_M[1, 1, λx...`, `df_M[1, 1, λx+1...`, `f[1, 1, λx...`, `f[1, 1, λx+1...`, that makes 4*81 = 324. Then there are four more arrays referenced at the start of the loop.

**Comment by chriselrod** [comment]
Writing an actual loop won't double count, and will allow it to not repeatedly reload from the same array.

`Base.broadcasted(+, a, a)` has the same type as `Base.broadcasted(+, a, b)` when `typeof(b) == typeof(a)`.
Meaning, you have to treat each repeated occurrence of the same array as a separate array -- because you can't tell they aren't the same one.

Of course, you could perhaps get really fancy in the `@turbo` macro to analyze the expression, and generate a different broadcast that somehow communicates which of the arrays are the same...

**Comment by chriselrod** [comment]
> Of course, you could perhaps get really fancy in the `@turbo` macro to analyze the expression, and generate a different broadcast that somehow communicates which of the arrays are the same...

If you want to take this route, I'd define an `AliasIDWrapper{ID,T}; x::T; end`.
You could then define
```julia
function add_broadcast!(
  ls::LoopSet,
  aliasdict::Dict{Int,Operation}, # or maybe just a vector 
  mC::Symbol,
  bcname::Symbol,
  loopsyms::Vector{Symbol},
  @nospecialize(arg::Type{AliasIDWrapper{ID,BC}}),
  dontbc,
  elementbytes::Int,
) where {ID,BC}
    get(aliasdict, ID) do
        add_broadcast!(aliasdict, mV, bcname, loopsyms, BC, dontbc, elementbytes)
    end
end
```
and add an `aliasdict` that you pass around everywhere.
You should also check if the destination you store into has an entry and matches a load.
In that case, you do need a different operation -- a store instead of a load -- but you can copy the `ArrayRef` from it so it has the same array ID.

Then when parsing a broadcast expression, you could add an `AliasIDWrapper`. You could do it in a single pass by having a `Dict{Symbol,Int}` and `get!`ing from it as you walk the broadcast expression.

**Comment by johnbcoughlin** [comment]
Thank you for your thoughtsThe reason for using a generated function to unroll this inner loop is that the matrices in question are extremely sparse, so in practice it seems to be absolutely worth it (like, 20x speedups worth it). For now I can do a stupid hack to generates 81*3+4 distinct ArrayReferences. This is good enough, but I am definitely interested in improving the story here along the lines of your suggestion, to hopefully save on loads.

Can you clarify why you are talking about broadcast expressions? I'm dealing with an explicit for loop, does LV somehow lower that to a broadcast internally?

**Comment by chriselrod** [comment]
> Can you clarify why you are talking about broadcast expressions? I'm dealing with an explicit for loop, does LV somehow lower that to a broadcast internally?

Sorry, I misunderstood/didn't look at the problem too closely.
Yes, every offset expression has a separate mref.
So having 

> `df_M[1, 1, λx...`, `df_M[1, 1, λx+1...`, `f[1, 1, λx...`, `f[1, 1, λx+1...`

would be 4 different array references, exactly as you said.

If any of this loading could be represented by a loop, that would help.
Otherwise, the focus should be on increasing the number of array references LV supports, as suggested initially.
