### ISSUE TITLE
`vcount` broken for `Vector{Bool}`

### ISSUE THREAD

**Issue by cafaxo** [JuliaSIMD/LoopVectorization.jl#479]
This behavior is incorrect:

```julia
julia> vcount([true])
0

julia> count([true])
1
```

**Comment by chriselrod** [comment]
The first argument needs to be a function. I should probably add an `vxount(x::AbstractArray) = vcount(identity, x)` method.

**Comment by cafaxo** [comment]
With `identity` as the first argument I get
```
julia> vcount(>(0), [true])
1

julia> vcount(identity, [true])
VectorizationBase.Vec{16, Int32}<1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>
```
This also does not seem right.
