### ISSUE TITLE
vfilter with multiple conditions

### ISSUE THREAD

**Issue by alfaromartino** [JuliaSIMD/LoopVectorization.jl#509]
It seems that `vfilter`, `vmap`, etc can't handle multiple conditions?

```
x       = rand(10)
cond(a) = ((a > 0.25) && (a < 0.75))

vfilter(cond,x) # ERROR: TypeError: non-boolean (VectorizationBase.Mask{4, UInt8}) used in boolean context
filter(cond,x)  # this works

vmap(cond,x)    # ERROR: TypeError: non-boolean (VectorizationBase.Mask{4, UInt8}) used in boolean context
map(cond,x)     # this works
```

Thanks

**Comment by chriselrod** [comment]
Use `&` and `|` rather than `&&` and `||`.

**Comment by chriselrod** [comment]
Let me know if you have any further issues.
Unfortunately, supporting `&&` and `||` is not possible without compiler magic.
LoopModels, the eventual successor to LoopVectorization.jl, will support those.

But LoopVectorization.jl is implemented largely using multiple dispatch, and it is not possible to overload `&&` and `||` as these are syntax, not functions.

As a word of caution, note that `&` and `|` don't have the same precedence as `&&` and `||`, so you'll have to be sure and add parenthesis whenever using them, like you did in your example.
